# BASE_DISTRIBUTION is used to switch between the old base distribution and distroless base images
ARG BASE_DISTRIBUTION=debug

# Version is the base image version from the TLD Makefile
ARG BASE_VERSION=latest
ARG ISTIO_BASE_REGISTRY=gcr.io/istio-release

# The following section is used as base image if BASE_DISTRIBUTION=debug
FROM ${ISTIO_BASE_REGISTRY}/base:${BASE_VERSION} AS debug

# The following section is used as base image if BASE_DISTRIBUTION=distroless
FROM ${ISTIO_BASE_REGISTRY}/iptables:${BASE_VERSION} AS distroless

# This will build the final image based on either debug or distroless from above
# hadolint ignore=DL3006
FROM ${BASE_DISTRIBUTION:-debug}

WORKDIR /

ARG proxy_version
ARG SIDECAR=envoy

# Copy Envoy bootstrap templates used by pilot-agent
COPY higress_envoy_bootstrap.json /var/lib/istio/envoy/envoy_bootstrap_tmpl.json
COPY higress_envoy_bootstrap_lite.json /var/lib/istio/envoy/envoy_bootstrap_lite_tmpl.json

# Install Envoy.
ARG TARGETARCH
COPY ${TARGETARCH:-amd64}/${SIDECAR} /usr/local/bin/${SIDECAR}

# Install MCP server Golang Filter
COPY ${TARGETARCH:-amd64}/golang-filter_${TARGETARCH:-amd64}.so /var/lib/istio/envoy/golang-filter.so

# Environment variable indicating the exact proxy sha - for debugging or version-specific configs
ENV ISTIO_META_ISTIO_PROXY_SHA=$proxy_version

ARG TARGETARCH
COPY ${TARGETARCH:-amd64}/pilot-agent /usr/local/bin/pilot-agent

RUN apt-get update --allow-unauthenticated && \
  apt-get install --no-install-recommends -y --allow-unauthenticated \
  logrotate \
  cron \
  && apt-get upgrade -y --allow-unauthenticated \
  && apt-get clean

# Latest releases available at https://github.com/aptible/supercronic/releases
ENV SUPERCRONIC_URL=https://github.com/higress-group/proxy/releases/download/v2.2.0/supercronic-linux-${TARGETARCH:-amd64} \
    SUPERCRONIC=supercronic-linux-${TARGETARCH:-amd64}

RUN curl -fsSLO "$SUPERCRONIC_URL" \
 && chmod +x "$SUPERCRONIC" \
 && mv "$SUPERCRONIC" "/usr/local/bin/${SUPERCRONIC}" \
 && ln -s "/usr/local/bin/${SUPERCRONIC}" /usr/local/bin/supercronic


COPY higress-proxy-start.sh /usr/local/bin/higress-proxy-start.sh

COPY higress-proxy-container-init.sh /usr/local/bin/higress-proxy-container-init.sh

RUN chmod a+x /usr/local/bin/higress-proxy-container-init.sh;/usr/local/bin/higress-proxy-container-init.sh

RUN chmod a+x /usr/local/bin/higress-proxy-start.sh

# The pilot-agent will bootstrap Envoy.
ENTRYPOINT ["/usr/local/bin/higress-proxy-start.sh"]
